### ISSUE TITLE
希望提供最新代码的release

### ISSUE THREAD

**Issue by hy101** [wozaiha/DalamudACT#6]
我没编译成功，能发布以下最新的版本吗？

**Comment by wozaiha** [comment]
目前的版本可以正常编译，如果大喇叭不认请删掉json文件手动加载

**Comment by hy101** [comment]
如何解决依赖问题，这个插件依赖Dalamud，然后Dalamud又依赖其他其他的包。
我试着找了一个cn版本的Dalamud.dll，结果加不到jetbrains Rider编译器里面去。
https://blog.csdn.net/weixin_45691803/article/details/112792353

**Comment by hy101** [comment]
能不能把你那边编译好的dll文件发到release里面

**Comment by wozaiha** [comment]
这本身就是基于Dalamud的插件啊，你始终是需要dalamud来运行它的，你直接把依赖目录指向本地的dalamud文件夹就应该可以处理掉所有依赖问题了
