### ISSUE TITLE
希望提供最新代码的release

### ISSUE THREAD

**Issue by ziegfeld** [wozaiha/DalamudACT#7]
wozaiha 您好 我是用的国际服版本，
添加了repo后dalamud安装器提醒年代过于久远，无法与当前版本框架兼容。

我看到最近都还有活跃的开发，
请问怎样可以帮你测试？

**Comment by wozaiha** [comment]
最近没续国际服月卡，我下周抽空去看一看

**Comment by wozaiha** [comment]
已提供最新版本release文件，目前未添加至repo，请手动加载
国际服未进行实际数值测试，仅保证可运行，如出现较大数值偏差请联系
[Release](https://github.com/wozaiha/DalamudACT/releases/tag/API9)
